### ISSUE TITLE
Updates? 

### ISSUE THREAD

**Issue by Happyfeet01** [ch1bo/garmin-otp-authenticator#3]
Hello,

do you plan more updates and features? Or is this project no longer in development?

**Comment by ch1bo** [comment]
Have you seen the 0.2.0 update? I also updated the Readme with potential next steps. Are you looking for something specific?

**Comment by phedoreanu** [comment]
@ch1bo Fenix 6 support ? 😁

**Comment by ch1bo** [comment]
@phedoreanu As I have also a new garmin watch (Vivoactive 3) and some time currently I guess I'll add support for more devices (CC #2) - especially also with round screen. Stay tuned

**Comment by LauH1987** [comment]
Would it be possible to make the app work with Garmin Forerunner 235?

**Comment by ch1bo** [comment]
Vivoactive 3 and Forerunner 245 are supported in the current version `1.0.1`. I am currently adding the vivoactive 4(s) and fenix 6 should not be too hard.

However Forerunner 235 does not have ConnectIQ version > 2.4? That would be hard to add, as this app is relying on the per-app encrypted application storage IIRC

**Comment by LauH1987** [comment]
@ch1bo Just updated to 8.10 (ba3b68e)

**Comment by ch1bo** [comment]
> @ch1bo Fenix 6 support ? grin

@phedoreanu 1.0.3 does support the fenix 6 series now. Please give it a try as I do not have such a beast of a watch ;) I would appreciate a positive review on the connectiq store!

---

> Would it be possible to make the app work with Garmin Forerunner 235?

@LauH1987 Supporting the FR235 is unfortunately not easily possible as it is still on a connectiq version `< 2.4.x`. In order to make it work, I would need to restructure the application and polyfill encryption to avoid extractability of 2fa secrets. If the latter is not so important to you I might eventually add support for it.. but don't you want a new watch anyways? :)

---

Given my recent development I'd say this is project can be considered active, thus closing this issue.
